---
image: nuetoban/crocodile:latest

env: ""
logLevel: TRACE
botToken: ""
webhookAddr: ""
webhookPath: ""
githubName: ""
githubToken: ""

postgresPassword: ""
postgresHostPath: ""
postgresNodeSelectorHostname: ""

redisHostPath: ""
redisNodeSelectorHostname: ""

domain: ""
backupChatID: "123456"
livenessProbeChatID: "123456"
